### ISSUE TITLE
Pie not showing at all even after disabling the new feature

### ISSUE THREAD

**Issue by GuardedHoney53** [AV306/KeybindsGalore-Plus#10]
I disabled the newly introduced feature but the pie is still not showing

i do not know how to reproduce it since it just randomly stopped working which i thought was caused by the new features

**System Information (please complete the following information):**
 - Windows
 - Minecraft Version: 1.21.1
 - KeybindsGalore+ Version 1.3.1+1.21.1
 - Too many to list down

I dont see any errors on the logs but i will put in here anyways
[latest.log](https://github.com/user-attachments/files/18151150/latest.log)

**Comment by AV306** [comment]
Hi @GuardedHoney53, thanks for the report! This is a very interesting issue so it might take a while to fix; so sorry for the inconvenience :(

**Comment by AV306** [comment]
This should be fixed now! Could I also trouble you to check out the "request for information" [here](https://github.com/AV306/KeybindsGalore-Plus/issues/7) to help me understand it better?

**Comment by GuardedHoney53** [comment]
hi uhm new issue, probably not related but 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-12-28 19:39:36
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_7353(net.minecraft.class_2561, boolean)" because "net.minecraft.class_310.method_1551().field_1724" is null
	at knot//net.minecraft.class_304.handler$ejl000$keybindsgaloreplus$setPressed(class_304.java:7066)
	at knot//net.minecraft.class_304.method_23481(class_304.java)
	at knot//net.minecraft.class_304.method_1425(class_304.java:122)
	at knot//net.minecraft.class_304.method_1437(class_304.java:63)
	at knot//net.minecraft.class_310.method_1507(class_310.java:1138)
	at knot//net.minecraft.class_310.<init>(class_310.java:687)
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_304.handler$ejl000$keybindsgaloreplus$setPressed(class_304.java:7066)
	at knot//net.minecraft.class_304.method_23481(class_304.java)
	at knot//net.minecraft.class_304.method_1425(class_304.java:122)
	at knot//net.minecraft.class_304.method_1437(class_304.java:63)
	at knot//net.minecraft.class_310.method_1507(class_310.java:1138)
	at knot//net.minecraft.class_310.<init>(class_310.java:687)
Mixins in Stacktrace:
	net.minecraft.class_304:
		io.bendy1234.fasttrading.mixin.KeyBindingAccessor (fasttrading.mixins.json)
		dev.tr7zw.itemswapper.mixin.KeyMappingMixin (itemswapper.mixins.json)
		gg.essential.mixins.transformers.client.settings.MixinKeyBinding (mixins.essential.json)
		me.av306.keybindsgaloreplus.mixin.KeyBindingMixin (keybindsgaloreplus.mixins.json)
		com.replaymod.core.mixin.KeyBindingAccessor (mixins.core.replaymod.json)
		marsh.town.brb.mixins.accessors.KeyMappingAccessor (mixins.brb-common.json)
		moe.nea.firmament.mixins.ToggleSprintPatch (firmament.mixins.json)
		net.blay09.mods.balm.mixin.FabricKeyMappingMixin (balm.fabric.mixins.json)
		net.blay09.mods.kuma.mixin.KeyMappingMixin (kuma_api.fabric.mixins.json)
		nl.enjarai.doabarrelroll.mixin.client.key.KeyBindingMixin (do_a_barrel_roll.mixins.json)
		com.replaymod.core.mixin.Mixin_ContextualKeyBindings (mixins.core.replaymod.json)
		net.diebuddies.mixins.settings.MixinKeyMappingAccessor (physicsmod.mixins.json)
		net.blay09.mods.balm.mixin.KeyMappingMixin (balm.fabric.mixins.json)
		net.fabricmc.fabric.mixin.client.keybinding.KeyBindingAccessor (fabric-key-binding-api-v1.mixins.json)
		net.blay09.mods.kuma.mixin.KeyMappingAccessor (kuma_api.mixins.json)
		me.av306.keybindsgaloreplus.mixin.KeyBindingAccessor (keybindsgaloreplus.mixins.json)
		net.blay09.mods.balm.mixin.KeyMappingAccessor (balm.fabric.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.KeyBindingAccessor (fabric-events-interaction-v0.client.mixins.json)
		nl.enjarai.doabarrelroll.mixin.client.key.KeyBindingAccessor (do_a_barrel_roll.mixins.json)
		com.github.breadmoirai.oneclickcrafting.mixin.KeyBindingAccessor (one-click-crafting.mixins.json)
		com.blamejared.controlling.mixin.AccessKeyMapping (controlling.mixins.json)
		gg.essential.mixins.transformers.client.options.KeyBindingAccessor (mixins.essential.json)
		net.frostbyte.inventory.mixin.KeyBindingMixin (inventory.mixins.json)
		com.provismet.tooltipscroll.mixin.KeyBindAccessor (toolscroll.mixins.json)
		fuzs.puzzleslib.fabric.mixin.client.KeyMappingFabricMixin (puzzleslib.fabric.mixins.json)
		fi.dy.masa.litematica.mixin.IMixinKeyBinding (mixins.litematica.json)
	net.minecraft.class_310:
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		fi.dy.masa.litematica.mixin.MixinMinecraftClient_easyPlace (mixins.litematica.json)
		com.natamus.collective.fabric.mixin.MinecraftMixin (collective_fabric.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		com.replaymod.render.mixin.Mixin_SuppressFramebufferResizeDuringRender (mixins.render.replaymod.json)
		traben.entity_sound_features.mixin.MixinResourceReload (entity_sound_features-common.mixins.json)
		de.florianmichael.viafabricplus.injection.mixin.fixes.minecraft.MixinMinecraftClient (viafabricplus.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.dynamic_resources.MinecraftMixin_ModelTicking (modernfix-common.mixins.json)
		com.replaymod.render.mixin.Mixin_UseGuiFramebufferDuringGuiRendering (mixins.render.replaymod.json)
		net.diebuddies.mixins.fabricapi.MixinMinecraft (physicsmod.mixins.json)
		net.replaceitem.symbolchat.mixin.MinecraftClientAccessor (symbol-chat.mixins.json)
		me.ramidzkh.fabrishot.mixins.MinecraftClientMixin (mixins.fabrishot.json)
		me.flashyreese.mods.sodiumextra.mixin.core.MixinMinecraftClient (sodium-extra.mixins.json)
		toni.sodiumdynamiclights.mixin.MinecraftClientMixin (mixins.sodiumdynamiclights.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientMixin (fastquit.mixins.json)
		dev.tr7zw.itemswapper.mixin.MinecraftMixin (itemswapper.mixins.json)
		com.koteinik.chunksfadein.mixin.misc.MinecraftMixin (chunksfadein.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		nl.enjarai.cicada.mixin.EntityRenderStateMixin (cicada.mixins.json)
		mezz.jei.fabric.mixin.MinecraftMixin (jei.mixins.json)
		ca.fxco.memoryleakfix.mixin.hugeScreenshotLeak.Minecraft_screenshotMixin (memoryleakfix.mixins.json)
		traben.entity_model_features.mixin.MixinResourceReloadEnd (entity_model_features-common.mixins.json)
		dlovin.inventoryhud.mixin.PlayerMixin (inventoryhud.mixins.json)
		smsk.smoothscroll.mixin.CreativeScreen.MinecraftClientMixin (smoothscroll.mixins.json)
		dev.imb11.sounds.mixin.ui.ScreenSoundEffect (sounds.mixins.json)
		net.xolt.freecam.mixins.MinecraftMixin (freecam-common.mixins.json)
		com.ishland.vmp.mixins.timesource.MixinMinecraftClient (vmp.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.fabric.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.Mixin_PassEvents_HandleKeybinds (mixins.jgui.json)
		net.raphimc.immediatelyfast.injection.mixins.core.MixinMinecraftClient (immediatelyfast-common.mixins.json)
		org.embeddedt.modernfix.common.mixin.feature.measure_time.MinecraftMixin (modernfix-common.mixins.json)
		de.hysky.skyblocker.mixins.MinecraftClientMixin (skyblocker.mixins.json)
		org.embeddedt.modernfix.fabric.mixin.feature.measure_time.MinecraftMixin_Fabric (modernfix-fabric.mixins.json)
		io.socol.betterthirdperson.mixin.MinecraftClientMixin (betterthirdperson.mixins.json)
		io.github.gaming32.worldhost.mixin.MixinMinecraft (world-host.mixins.json)
		me.ichun.mods.ichunutil.mixin.client.MinecraftMixin (ichunutil.mixins.json)
		net.mehvahdjukaar.moonlight.core.mixins.MinecraftMixin (moonlight-common.mixins.json)
		com.nettakrim.spyglass_astronomy.mixin.MinecraftClientMixin (spyglass_astronomy.mixins.json)
		com.anthonyhilyard.prism.mixin.MinecraftMixin (prism.mixins.json)
		org.embeddedt.modernfix.fabric.mixin.core.MCMixin_Fabric (modernfix-fabric.mixins.json)
		com.noxcrew.noxesium.mixin.ui.render.MinecraftMixin (noxesium.mixins.json)
		betteradvancements.mixin.MinecraftMixin (betteradvancements.mixins.json)
		com.spyxar.tiptapshow.mixin.MinecraftClientMixin (tiptapshow.mixins.json)
		dev.tr7zw.waveycapes.mixin.PlayerRenderStateMixin (waveycapes.mixins.json)
		com.replaymod.replay.mixin.Mixin_HandleInputsInReplay (mixins.replay.replaymod.json)
		net.irisshaders.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (iceberg.mixins.json)
		dev.emi.emi.mixin.MinecraftClientMixin (emi.mixins.json)
		squeek.appleskin.mixin.MinecraftClientMixin (appleskin.mixins.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		fuzs.puzzleslib.fabric.mixin.client.MinecraftFabricMixin (puzzleslib.fabric.mixins.json)
		gg.essential.mixins.transformers.client.gui.Mixin_FixKeybindUnpressedInEmoteWheel (mixins.essential.json)
		traben.entity_model_features.mixin.accessor.MinecraftClientAccessor (entity_model_features-common.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		xaero.map.mixin.MixinMinecraftClient (xaeroworldmap.mixins.json)
		mod.crend.libbamboo.mixin.MinecraftClientMixin (libbamboo-common.mixins.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (yacl.mixins.json)
		com.aizistral.nochatreports.common.mixins.client.MixinMinecraft (mixins/common/nochatreports.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		moe.nea.firmament.mixins.ScreenChangeEventPatch (firmament.mixins.json)
		net.irisshaders.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		net.anvian.sodiumextrainformation.mixin.EndTickMixin (sodiumextrainformation.mixins.json)
		moe.nea.firmament.mixins.ResourceReloaderRegistrationPatch (firmament.mixins.json)
		gg.essential.mixins.transformers.client.MixinMinecraft (mixins.essential.json)
		dev.isxander.debugify.client.mixins.basic.mc46766.MinecraftMixin (debugify.client.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.world_leaks.MinecraftMixin (modernfix-common.mixins.json)
		com.replaymod.lib.de.johni0702.minecraft.gui.versions.mixin.MixinMinecraft (mixins.jgui.json)
		me.replet.client.Mixins.MinecraftClientClassMixin (vanillafix.crashui.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin (optigui.mixins.json)
		net.treset.vanillaconfig.mixin.MinecraftClientMixin (vanillaconfig.mixins.json)
		gg.essential.mixins.transformers.compatibility.vanilla.Mixin_WorkaroundBrokenFramebufferBlitBlending (mixins.essential.json)
		org.embeddedt.modernfix.common.mixin.feature.remove_telemetry.MinecraftMixin_Telemetry (modernfix-common.mixins.json)
		toni.sodiumextras.mixins.impl.fps.GpuUsageMixin (mixins.sodiumextras.json)
		com.aizistral.nochatreports.fabric.mixins.client.MixinMinecraft (mixins/fabric/nochatreports-fabric.mixins.json)
		de.dafuqs.paginatedadvancements.mixin.MinecraftClientMixin (paginatedadvancements.mixins.json)
		foundationgames.enhancedblockentities.mixin.MinecraftClientMixin (enhancedblockentities.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		dev.chachy.lazylanguageloader.client.mixin.optimizations.splash.MixinMinecraftClient (lazy-language-loader.mixin.json)
		net.uku3lig.ukulib.mixin.MixinMinecraftClient (ukulib.mixins.json)
		org.ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		gg.essential.mixins.transformers.client.Mixin_IncreaseMenuFpsLimit (mixins.essential.json)
		fabric.cc.cassian.clickthrough.mixins.ItemUseMixin (fabric-clickthrough.mixins.json)
		net.irisshaders.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json)
		io.github.cottonmc.cotton.gui.impl.mixin.client.MinecraftClientMixin (mixins.libgui.json)
		com.sonicether.soundphysics.mixin.MinecraftMixin (sound_physics_remastered.mixins.json)
		gg.essential.mixins.transformers.client.gui.Mixin_RecalculateMenuScale (mixins.essential.json)
		bettercommandblockui.mixin.MinecraftClientMixin (bettercommandblockui.mixins.json)
		dev.tr7zw.notenoughanimations.mixins.LivingRenderStateMixin (notenoughanimations.mixins.json)
		xyz.pupbrained.mixin.HotbarSwitchMixin (drop_confirm.mixins.json)
		de.hysky.skyblocker.mixins.accessors.MinecraftClientAccessor (skyblocker.mixins.json)
		net.tape.timm.mixin.ClientTickMixin (timm.mixins.json)
		com.minecraftserverzone.weaponmaster.mixin.MinecraftModMixin (weaponmaster_ydm.mixins.json)
		de.florianmichael.viafabricplus.injection.mixin.base.integration.MixinMinecraftClient (viafabricplus.mixins.json)
		net.caffeinemc.mods.sodium.mixin.core.MinecraftMixin (sodium-common.mixins.json)
		gg.essential.mixins.transformers.feature.skin_overwrites.Mixin_InstallTrustingServicesKeyInfo (mixins.essential.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		ca.fxco.moreculling.mixin.Minecraft_managersMixin (moreculling.mixins.json)
		com.seibel.distanthorizons.fabric.mixins.client.MixinMinecraft (fabric-DistantHorizons.fabric.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		com.replaymod.core.mixin.MinecraftAccessor (mixins.core.replaymod.json)
		dev.terminalmc.autoreconnectrf.mixin.MixinMinecraft (autoreconnectrf.mixins.json)
		org.embeddedt.modernfix.common.mixin.bugfix.concurrency.MinecraftMixin (modernfix-common.mixins.json)
		com.noxcrew.noxesium.mixin.feature.component.ext.MinecraftExt (noxesium.mixins.json)
		net.diebuddies.mixins.MixinMinecraft (physicsmod.mixins.json)
		io.github.thecsdev.tcdcommons.client.mixin.events.MixinMinecraftClient (tcdcommons.client.mixin.events.json)
		fi.dy.masa.tweakeroo.mixin.MixinMinecraftClient (mixins.tweakeroo.json)
		org.redlance.dima_dencep.mods.rrls.mixins.MinecraftClientMixin (rrls.mixins.json)
		info.u_team.u_team_core.intern.mixin.MinecraftMixin (uteamcore.mixins.json)
		xaero.common.mixin.MixinMinecraftClient (xaerohud.mixins.json)
		com.replaymod.core.mixin.MixinMinecraft (mixins.core.replaymod.json)
		ca.fxco.moreculling.mixin.blockstates.Minecraft_loadBlocksMixin (moreculling.mixins.json)
		mod.crend.libbamboo.mixin.MinecraftClientAccessor (libbamboo-common.mixins.json)
		net.diebuddies.mixins.cloth.MixinMinecraft (physicsmod.mixins.json)
		com.blamejared.controlling.mixin.OpenGuiMixin (controlling.fabric.mixins.json)
		dynamic_fps.impl.mixin.MinecraftMixin (dynamic_fps-common.mixins.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		net.thomilist.showdurability.mixin.client.SaveSettingsMixin (showdurability.client.mixins.json)
		com.kingcontaria.fastquit.mixin.MinecraftClientAccessor (fastquit.mixins.json)
		com.minelittlepony.common.mixin.MixinMinecraftClient (kirin.mixin.json)
		fi.dy.masa.litematica.mixin.MixinMinecraftClient (mixins.litematica.json)
		gg.essential.mixins.transformers.feature.emote.Mixin_AllowMovementDuringEmoteWheel_HandleKeybinds (mixins.essential.json)
		traben.entity_model_features.mixin.MixinResourceReloadStart (entity_model_features-common.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		org.embeddedt.modernfix.common.mixin.perf.dedicated_reload_executor.MinecraftMixin (modernfix-common.mixins.json)
		io.github.gaming32.worldhost.mixin.MinecraftAccessor (world-host.mixins.json)
		gg.essential.mixins.transformers.client.Mixin_RunEssentialTasks (mixins.essential.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		net.kosmo.music.impl.fabric.mixin.MixinMinecraftClient (musicnotification.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		ca.fxco.memoryleakfix.mixin.targetEntityLeak.Minecraft_targetClearMixin (memoryleakfix.mixins.json)
		com.minenash.monsters_in_the_closet.mixin.MinecraftClientMixin (monsters_in_the_closet.mixins.json)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		DWMAPI.DLL:Microsoft Desktop Window Manager API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL Utility Library DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		MSASN1.dll:ASN.1 Runtime APIs:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24090.11 (26d75470953920f90fd0438874501e9d9a31e621):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		OWExplorer.dll:Overlay:2.2.263.0:Overwolf LTD
		OpenAL.dll:Main implementation library:1.23.1:
		POWRPROF.dll:Power Profile Helper DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		PhysXCommon_64.dll:PhysXCommon 32bit Dynamic Link Library:5.3.1.0:NVIDIA Corporation
		PhysXCooking_64.dll:PhysXCooking 32bit Dynamic Link Library:5.3.1.0:NVIDIA Corporation
		PhysXDevice64.dll:NVIDIA PhysX Device Module:18, 12, 7, 2:NVIDIA Corporation
		PhysXFoundation_64.dll:PhysXFoundation 32bit Dynamic Link Library:5.3.1.0:NVIDIA Corporation
		PhysXGpu_64.dll:PhysXGpu 32bit Dynamic Link Library:5.3.1.0:NVIDIA Corporation
		PhysXJniBindings_64.dll
		PhysX_64.dll:PhysX 32bit Dynamic Link Library:5.3.1.0:NVIDIA Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		RTSSHooks64.dll
		SHCORE.dll:SHCORE:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.26100.1301 (WinBuild.160101.0800):Microsoft Corporation
		Start10_64.dll:Start button for Windows 10/11:2.1.1.0:Stardock Software, Inc
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.26100.1301 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		cryptnet.dll:Crypto Network Related API:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		directxdatabasehelper.dll:DirectXDatabaseHelper:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		drvstore.dll:Driver Store API:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		fastprox.dll:WMI Custom Marshaller:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		gpapi.dll:Group Policy Client API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		icm32.dll:Microsoft Color Management Module (CMM):10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		imagehlp.dll:Windows NT Image Helper:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		javaw.exe:Java(TM) Platform SE binary:22.0.2.0:N/A
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		jli.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		jna2125125384903363592.dll:JNA native library:7.0.0:Java(TM) Native Access (JNA)
		jsvml.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:22.0.2.0:N/A
		kernel.appcore.dll:AppModel API Host:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		libbattery-jni-1.2.0+amd64.windows.dll
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		management_ext.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		mdnsNSP.dll:Bonjour Namespace Provider:3,0,0,10:Apple Inc.
		mscms.dll:Microsoft Color Matching System DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		nio.dll:Java(TM) Platform SE binary:22.0.2.0:N/A
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		nvapi64.dll:NVIDIA NVAPI Library, Version 566.14 :32.0.15.6614:NVIDIA Corporation
		nvcuda.dll:NVIDIA CUDA Driver, Version 566.14 :32.0.15.6614:NVIDIA Corporation
		nvcuda64.dll:NVIDIA CUDA Driver, Version 566.14 :32.0.15.6614:NVIDIA Corporation
		nvdxgdmal64.dll
		nvgpucomp64.dll:NVIDIA GPU Compiler Driver, Version 566.14 :32.0.15.6614:NVIDIA Corporation
		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:32.0.15.6614:NVIDIA Corporation
		nvspcap64.dll:NVIDIA Game Proxy

**Comment by GuardedHoney53** [comment]
also the thing u requested
[crash-2024-12-28_22.07.51-client.txt](https://github.com/user-attachments/files/18266416/crash-2024-12-28_22.07.51-client.txt)
[latest.log](https://github.com/user-attachments/files/18266415/latest.log)

**Comment by AV306** [comment]
Hi @GuardedHoney53, this is a duplicate of #12 which should be fixed in v1.3.3!

The new release might not actually fix your original bug, though; please test it and let me know if the bug persists!

(reopening so that I don’t miss anything)

**Comment by GuardedHoney53** [comment]
I will troubleshoot it soon and get back to you! thanks for the help :)

**Comment by AV306** [comment]
Oh yeah, please set “debug=true” in your config file if you do have issues!
I made most of the log messages only print when debug mode is enabled to prevent log spam :)

**Comment by AV306** [comment]
Hi @GuardedHoney53, I'm closing this issue for now; please don't hesitate to reopen it if you find any bugs!
